# Generated by Django 5.2.7 on 2025-11-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=30, unique=True)),
                ('consultas_marcadas', models.JSONField()),
            ],
        ),
    ]
