# Generated by Django 5.2.7 on 2025-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='consultas_marcadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
