# Generated by Django 5.2.7 on 2025-11-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0002_alter_userregister_consultas_marcadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='consultas_marcadas',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento_calendar', models.CharField(max_length=255, unique=True, verbose_name='ID do Google Calendar')),
                ('date', models.DateField(verbose_name='Data da Consulta')),
                ('time', models.TimeField(verbose_name='Hora da Consulta')),
                ('appointment_number', models.IntegerField(verbose_name='Número Sequencial (UX)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='chatbot_api.userregister', verbose_name='Dono da Consulta')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['appointment_number'],
            },
        ),
    ]
