# Generated by Django 5.2.7 on 2025-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0003_remove_userregister_consultas_marcadas_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='appointment1_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora 1ª Consulta'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='appointment1_gcal_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Google Calendar 1'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='appointment2_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora 2ª Consulta'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='appointment2_gcal_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Google Calendar 2'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
